### ISSUE TITLE
Sprint Meeting Note 링크 깨짐

### ISSUE THREAD

**Issue by ChangJoo-Park** [huiseoul/welcome#4]
https://github.com/huiseoul/hsMobile/wiki

README.md 하단의 스프린트 미팅 노트의 링크가 잘못된 url을 가리키고 있는 것 같습니다

**Comment by johnwook** [comment]
@ChangJoo-Park 안녕하세요! 이슈 제보해주셔서 감사합니다. 현재 해당 링크는 private repo 주소로 huiseoul engineer 만 접근이 가능합니다. README.md 에 업데이트 해야겠네요 :)

**Comment by johnwook** [comment]
https://github.com/huiseoul/welcome/commit/86bafe6f01dd40bc7d3a52005d3415f3339f7a22 commit 을 추가했습니다! 이에 해당 이슈는 닫겠습니다. 감사합니다.

**Comment by ChangJoo-Park** [comment]
확인해주셔서 감사합니다 :)
